spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sarim915602
    url: jdbc:mysql://localhost:3306/fyp_student_portal

  application:
    name: FYP-PROJECT

server:
  port: 8080
  servlet:
    context-path: /api/v1

com:
  fyp:
    studentportal:
      jwt: thisisthejwtsecretkey